/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kavin
 */
public class SubMarine extends javax.swing.JFrame implements DefenseInterface  {
    private MainController m1;
    /**
     * Creates new form SubMarine
     * @param m1
     */
    public SubMarine(MainController m1) {
        this.m1=m1;
        initComponents();
        setVisible(true);
    }
    @Override
     public void clearArea(){
       Lbl1Submarine.setText("Area cleared");
    }
        public boolean isPosition(){
        return CheckSubmarine.isSelected();
        };
    
    @Override
    public void enableButtons(int value){
        if(isPosition()){
            if(value>=20){
                BtnSubmarine1.setEnabled(true);
            }
            if(value>=40){
                BtnSubmarine2.setEnabled(true);
            }
            if(value>=60){
                BtnSubmarine3.setEnabled(true);
            }
            if(value>=80){
                BtnSubmarine4.setEnabled(true);
            }
           
        }
    }
    @Override
    public void appendMessage(String message){
        AreaSubmarine.append(message+"\n");
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl1Submarine = new javax.swing.JLabel();
        BtnSubmarine1 = new javax.swing.JButton();
        BtnSubmarine2 = new javax.swing.JButton();
        BtnSubmarine3 = new javax.swing.JButton();
        BtnSubmarine4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaSubmarine = new javax.swing.JTextArea();
        TextSubmarine = new javax.swing.JTextField();
        SendSubmarine = new javax.swing.JButton();
        Slider2Submarine = new javax.swing.JSlider();
        Lbl2Submarine = new javax.swing.JLabel();
        Lbl3Submarine = new javax.swing.JLabel();
        Spinner1Submarine = new javax.swing.JSpinner();
        Spinner2Submarine = new javax.swing.JSpinner();
        CheckSubmarine = new javax.swing.JCheckBox();
        Slider1Submarine = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Submarine");

        Lbl1Submarine.setText("Area not cleared");

        BtnSubmarine1.setText("Shoot");
        BtnSubmarine1.setEnabled(false);

        BtnSubmarine2.setText("Sonar Operation");
        BtnSubmarine2.setEnabled(false);

        BtnSubmarine3.setText("Tomohawk Missile");
        BtnSubmarine3.setEnabled(false);

        BtnSubmarine4.setText("Trident-2 Missile");
        BtnSubmarine4.setEnabled(false);
        BtnSubmarine4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmarine4ActionPerformed(evt);
            }
        });

        AreaSubmarine.setColumns(20);
        AreaSubmarine.setRows(5);
        jScrollPane1.setViewportView(AreaSubmarine);

        TextSubmarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSubmarineActionPerformed(evt);
            }
        });

        SendSubmarine.setText("Send");
        SendSubmarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendSubmarineActionPerformed(evt);
            }
        });

        Slider2Submarine.setOrientation(javax.swing.JSlider.VERTICAL);

        Lbl2Submarine.setText("Soldier Count");

        Lbl3Submarine.setText("Ammo Count");

        CheckSubmarine.setText("Position");
        CheckSubmarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSubmarineActionPerformed(evt);
            }
        });

        Slider1Submarine.setOrientation(javax.swing.JSlider.VERTICAL);

        jLabel3.setText("Energy");

        jLabel4.setText("Oxygen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SendSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(CheckSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(BtnSubmarine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BtnSubmarine3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BtnSubmarine4)
                                                .addGap(128, 128, 128))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(BtnSubmarine2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Lbl2Submarine)
                                                    .addComponent(Lbl3Submarine))
                                                .addGap(18, 18, 18))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Lbl1Submarine, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(270, 270, 270)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Spinner2Submarine, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Spinner1Submarine, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Slider1Submarine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Slider2Submarine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Lbl1Submarine)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Spinner1Submarine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl2Submarine))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnSubmarine1)
                                    .addComponent(BtnSubmarine2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnSubmarine3)
                                    .addComponent(BtnSubmarine4))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lbl3Submarine, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Spinner2Submarine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckSubmarine)
                                .addGap(28, 28, 28)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SendSubmarine)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Slider1Submarine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Slider2Submarine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSubmarine4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmarine4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSubmarine4ActionPerformed

    private void TextSubmarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSubmarineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSubmarineActionPerformed

    private void SendSubmarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendSubmarineActionPerformed
        m1.setTextArea("Submarine:"+TextSubmarine.getText()+"\n");// TODO add your handling code here:
    }//GEN-LAST:event_SendSubmarineActionPerformed

    private void CheckSubmarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSubmarineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckSubmarineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubMarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubMarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubMarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubMarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SubMarine().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaSubmarine;
    private javax.swing.JButton BtnSubmarine1;
    private javax.swing.JButton BtnSubmarine2;
    private javax.swing.JButton BtnSubmarine3;
    private javax.swing.JButton BtnSubmarine4;
    private javax.swing.JCheckBox CheckSubmarine;
    private javax.swing.JLabel Lbl1Submarine;
    private javax.swing.JLabel Lbl2Submarine;
    private javax.swing.JLabel Lbl3Submarine;
    private javax.swing.JButton SendSubmarine;
    private javax.swing.JSlider Slider1Submarine;
    private javax.swing.JSlider Slider2Submarine;
    private javax.swing.JSpinner Spinner1Submarine;
    private javax.swing.JSpinner Spinner2Submarine;
    private javax.swing.JTextField TextSubmarine;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
