/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kavin
 */
public class Helicopter extends javax.swing.JFrame implements DefenseInterface  {
    private MainController m1;
    /**
     * Creates new form Helicopter
     * @param m1
     */
    public Helicopter(MainController m1) {
        this.m1=m1;
        initComponents();
        setVisible(true);
    }
    @Override
     public void clearArea(){
       Lbl1Helicopter.setText("Area cleared");
    }
       public boolean isPosition(){
        return CheckHelicopter.isSelected();
        };
    
    @Override
    public void enableButtons(int value){
        if(isPosition()){
            if(value>=20){
                BtnHelicopter1.setEnabled(true);
            }
            if(value>=40){
                BtnHelicopter2.setEnabled(true);
            }
            if(value>=60){
                BtnHelicopter3.setEnabled(true);
            }
           
        }
    }
    @Override
    public void appendMessage(String message){
        AreaHelicopter.append(message+"\n");
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        TextHelicopter = new javax.swing.JTextField();
        SendHelicopter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaHelicopter = new javax.swing.JTextArea();
        BtnHelicopter1 = new javax.swing.JButton();
        BtnHelicopter2 = new javax.swing.JButton();
        BtnHelicopter3 = new javax.swing.JButton();
        SliderHelicopter = new javax.swing.JSlider();
        Lbl2Helicopter = new javax.swing.JLabel();
        Lbl3Helicopter = new javax.swing.JLabel();
        Spinner1Helicopter = new javax.swing.JSpinner();
        Spinner2Helicopter = new javax.swing.JSpinner();
        CheckHelicopter = new javax.swing.JCheckBox();
        Lbl1Helicopter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Helicopter");

        TextHelicopter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextHelicopterActionPerformed(evt);
            }
        });

        SendHelicopter.setText("Send");
        SendHelicopter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendHelicopterActionPerformed(evt);
            }
        });

        AreaHelicopter.setColumns(20);
        AreaHelicopter.setRows(5);
        jScrollPane1.setViewportView(AreaHelicopter);

        BtnHelicopter1.setText("Shoot");
        BtnHelicopter1.setEnabled(false);
        BtnHelicopter1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BtnHelicopter1StateChanged(evt);
            }
        });

        BtnHelicopter2.setText("Missile Operation");
        BtnHelicopter2.setEnabled(false);
        BtnHelicopter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHelicopter2ActionPerformed(evt);
            }
        });

        BtnHelicopter3.setText("Laser Operation");
        BtnHelicopter3.setEnabled(false);

        SliderHelicopter.setOrientation(javax.swing.JSlider.VERTICAL);

        Lbl2Helicopter.setText("Soldier Count");

        Lbl3Helicopter.setText("Ammo Count");

        CheckHelicopter.setText("Position");

        Lbl1Helicopter.setText("Area not cleared");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnHelicopter1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl1Helicopter, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnHelicopter2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl2Helicopter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Spinner1Helicopter, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckHelicopter, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl3Helicopter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Spinner2Helicopter, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnHelicopter3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextHelicopter, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SendHelicopter, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(SliderHelicopter, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SliderHelicopter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl2Helicopter)
                            .addComponent(Spinner1Helicopter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl1Helicopter))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Spinner2Helicopter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnHelicopter1)
                                .addComponent(BtnHelicopter2)
                                .addComponent(Lbl3Helicopter)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnHelicopter3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(CheckHelicopter, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextHelicopter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SendHelicopter))
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextHelicopterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextHelicopterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextHelicopterActionPerformed

    private void BtnHelicopter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHelicopter2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHelicopter2ActionPerformed

    private void SendHelicopterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendHelicopterActionPerformed
         m1.setTextArea("Helicopter:"+TextHelicopter.getText()+"\n");        // TODO add your handling code here:
    }//GEN-LAST:event_SendHelicopterActionPerformed

    private void BtnHelicopter1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BtnHelicopter1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHelicopter1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Helicopter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaHelicopter;
    private javax.swing.JButton BtnHelicopter1;
    private javax.swing.JButton BtnHelicopter2;
    private javax.swing.JButton BtnHelicopter3;
    private javax.swing.JCheckBox CheckHelicopter;
    private javax.swing.JLabel Lbl1Helicopter;
    private javax.swing.JLabel Lbl2Helicopter;
    private javax.swing.JLabel Lbl3Helicopter;
    private javax.swing.JButton SendHelicopter;
    private javax.swing.JSlider SliderHelicopter;
    private javax.swing.JSpinner Spinner1Helicopter;
    private javax.swing.JSpinner Spinner2Helicopter;
    private javax.swing.JTextField TextHelicopter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
