/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kavin
 */
public class Tank extends javax.swing.JFrame implements DefenseInterface{

    private MainController m1;/**
     * Creates new form Tank
     */

    /**
     * Creates new form Tank
     * @param m1
     */
    public Tank(MainController m1) {
        this.m1=m1;
        initComponents();
        setVisible(true);
    }
    @Override
    public void clearArea(){
       Lbl1Tank.setText("Area cleared");
    }
    public boolean isPosition(){
        return CheckTank.isSelected();
        };
    
    @Override
    public void enableButtons(int value){
        if(isPosition()){
            if(value>=20){
                BtnTank1.setEnabled(true);
            }
            if(value>=40){
                BtnTank2.setEnabled(true);
            }
            if(value>=60){
                BtnTank3.setEnabled(true);
            }
            if(value>=80){
                BtnTank4.setEnabled(true);
            }
        }   
    }
    
    @Override
    public void appendMessage(String message){
        AreaTank.append(message+"\n");
    }
            
        
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl1Tank = new javax.swing.JLabel();
        BtnTank1 = new javax.swing.JButton();
        BtnTank2 = new javax.swing.JButton();
        BtnTank3 = new javax.swing.JButton();
        BtnTank4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTank = new javax.swing.JTextArea();
        TextTank = new javax.swing.JTextField();
        SendTank = new javax.swing.JButton();
        SliderTank = new javax.swing.JSlider();
        Lbl2Tank = new javax.swing.JLabel();
        Lbl3Tank = new javax.swing.JLabel();
        Spinner1Tank = new javax.swing.JSpinner();
        Spinner2Tank = new javax.swing.JSpinner();
        CheckTank = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tank");

        Lbl1Tank.setText("Area not cleared");

        BtnTank1.setText("Shoot");
        BtnTank1.setEnabled(false);
        BtnTank1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTank1ActionPerformed(evt);
            }
        });

        BtnTank2.setText("Missile Operation");
        BtnTank2.setEnabled(false);
        BtnTank2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTank2ActionPerformed(evt);
            }
        });

        BtnTank3.setText("Redar Operation");
        BtnTank3.setEnabled(false);

        BtnTank4.setText("Rotate Shooting");
        BtnTank4.setEnabled(false);

        AreaTank.setColumns(20);
        AreaTank.setRows(5);
        jScrollPane1.setViewportView(AreaTank);

        SendTank.setText("Send");
        SendTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendTankActionPerformed(evt);
            }
        });

        SliderTank.setOrientation(javax.swing.JSlider.VERTICAL);

        Lbl2Tank.setText("Soldier Count");

        Lbl3Tank.setText("Ammo Count");

        CheckTank.setText("Position");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl1Tank, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnTank1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnTank2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnTank3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnTank4)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Lbl3Tank)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Spinner2Tank, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Lbl2Tank)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Spinner1Tank, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckTank, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TextTank)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SendTank))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(SliderTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl2Tank)
                    .addComponent(Lbl1Tank)
                    .addComponent(Spinner1Tank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(SliderTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnTank1)
                                    .addComponent(BtnTank2)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lbl3Tank)
                                    .addComponent(Spinner2Tank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnTank3)
                                .addComponent(BtnTank4))
                            .addComponent(CheckTank))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SendTank))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTank1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTank1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTank1ActionPerformed

    private void BtnTank2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTank2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTank2ActionPerformed

    private void SendTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendTankActionPerformed
         m1.setTextArea("Tank:"+TextTank.getText()+"\n");        // TODO add your handling code here:
    }//GEN-LAST:event_SendTankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTank;
    private javax.swing.JButton BtnTank1;
    private javax.swing.JButton BtnTank2;
    private javax.swing.JButton BtnTank3;
    private javax.swing.JButton BtnTank4;
    private javax.swing.JCheckBox CheckTank;
    private javax.swing.JLabel Lbl1Tank;
    private javax.swing.JLabel Lbl2Tank;
    private javax.swing.JLabel Lbl3Tank;
    private javax.swing.JButton SendTank;
    private javax.swing.JSlider SliderTank;
    private javax.swing.JSpinner Spinner1Tank;
    private javax.swing.JSpinner Spinner2Tank;
    private javax.swing.JTextField TextTank;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
